twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        SPOTIFY_REFRESH_TOKEN: AQBc71diMFaEa0KGKE2kEwXU9CAZLgePBEFQLjcHS--PV_SKFKLM6UvZ7iOsPIRbxSGQXMCitFB-pi-qyaaqg74ErMK8P7Z5vlSKIUwBpy2l3lOv6vz5NuEh8vl3_SmJ8a0

when@test:
    twig:
        strict_variables: true
